project_name: lancache-diagnostics

archives:
  - id: lancache-diagnostics
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    gcflags:
      - -trimpath
    ldflags:
      - -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapshot:
  name_template: "{{ .ProjectName }}-v{{ incpatch .Version }}"
